import type { Animal, LevelConfig, Step, ThemeMoment, World } from './level';

function meetAnimal(
  id: string, act: number, world: World, type: ThemeMoment['type'], focus: Animal | 'animals',
  title: string, npc: string, translation: string, target: string, meaning: string,
  coach: string, success: string, praise: string,
): Step {
  return { id, act, world, kind: 'say', title, npc, translation, target, meaning,
    coach, tip: coach, effect: 'animals', success, praise, moment: { type, focus },
    holdMs: type === 'animal-party' ? 5800 : type === 'animal-fish-window' ? 4800 : 4000 };
}

/** Original preschool adventure inspired by the Animals theme; not a textbook transcription. */
export const LEVEL_6: LevelConfig = {
  id: 6, title: '动物救助站', theme: 'animals', spells: false,
  intro: {
    heading: '叫一叫小动物，<br>和艾莎照顾新朋友！',
    description: '小猫在打盹，小狗想玩球，水塘里的朋友也在等你。用声音和六只小动物交朋友，最后一起去月光营地参加派对。',
  },
  units: ['BF1-U7'], starStepIds: ['a-see-cat', 'a-see-fish', 'a-finale'],
  acts: [
    { title: '彩虹救助站', subtitle: 'Wake up, little friends', icon: 'heart', world: 'animals-shelter', unit: 'BF1-U7' },
    { title: '泡泡水塘', subtitle: 'Wings, ripples & bubbles', icon: 'leaf', world: 'animals-pond', unit: 'BF1-U7' },
    { title: '月光动物营地', subtitle: 'I like animals!', icon: 'sparkles', world: 'animals-camp', unit: 'BF1-U7' },
  ],
  steps: [
    meetAnimal('a-cat', 0, 'animals-shelter', 'animal-cat-wake', 'cat',
      '轻轻叫醒打盹的小猫', 'A sleepy cat!', '一只困困的小猫！', 'Cat!', '小猫！',
      '轻轻说小猫的英语，叫它起来伸个懒腰。',
      '小猫睁开眼睛，伸了个大大的懒腰，和你打招呼啦！', 'Good!'),
    meetAnimal('a-dog', 0, 'animals-shelter', 'animal-dog-fetch', 'dog',
      '请小狗送来软软的球', 'The dog wants to play.', '小狗想玩耍。', 'Dog!', '小狗！',
      '说说小狗的英语，请它把球送给团团。',
      '小狗叼着球跑过来，团团接到了小狗送来的礼物！', 'Great job!'),
    meetAnimal('a-rabbit', 0, 'animals-shelter', 'animal-rabbit-hop', 'rabbit',
      '让小兔子跳过来打招呼', 'Here comes a rabbit!', '小兔子来啦！', 'Rabbit!', '兔子！',
      '叫一声兔子的英语，请它跳过来打招呼。',
      '小兔子一跳、两跳，跳到软垫上，长耳朵也跟着晃起来。', 'Well done!'),
    meetAnimal('a-see-cat', 0, 'animals-shelter', 'animal-cat-peek', 'cat',
      '和小猫玩躲猫猫', 'What do you see?', '你看见什么？', 'I see a cat.', '我看见一只小猫。',
      '跟艾莎说我看见一只小猫，请它探出头。',
      '躲猫猫！小猫从帐篷旁边探出来，送给你第一颗动物星光。', 'Amazing!'),
    meetAnimal('a-bird', 1, 'animals-pond', 'animal-bird-fly', 'bird',
      '请蓝色小鸟飞一圈', 'Look! A little bird!', '看，一只小鸟！', 'Bird!', '小鸟！',
      '叫一声小鸟的英语，请它飞过水塘。',
      '小鸟张开蓝蓝的翅膀，飞过水塘，又轻轻落在树枝上。', 'Good!'),
    meetAnimal('a-duck', 1, 'animals-pond', 'animal-duck-paddle', 'duck',
      '让小鸭子划着叶子船', 'A duck in the pond!', '水塘里有一只鸭子！', 'Duck!', '鸭子！',
      '说说鸭子的英语，请它带叶子小船去兜风。',
      '小鸭子游起来啦！叶子小船跟在后面，水面出现一圈圈小波纹。', 'Cool!'),
    meetAnimal('a-fish', 1, 'animals-pond', 'animal-fish-swim', 'fish',
      '请小鱼穿过泡泡圈', 'A fish is swimming.', '一条鱼正在游泳。', 'Fish!', '鱼！',
      '说说鱼的英语，请小鱼穿过泡泡圈。',
      '小鱼摆摆尾巴，从泡泡圈里游过去，吐出了好多小泡泡！', 'Well done!'),
    meetAnimal('a-see-fish', 1, 'animals-pond', 'animal-fish-window', 'fish',
      '打开小鱼的泡泡窗口', 'Can you see the fish?', '你看见小鱼了吗？', 'I see a fish.', '我看见一条鱼。',
      '跟艾莎说我看见一条鱼，打开泡泡窗口。',
      '泡泡窗口亮起来，小鱼在清清的水里转了一圈。第二颗动物星光亮啦！', 'Amazing!'),
    meetAnimal('a-cat-brush', 2, 'animals-camp', 'animal-cat-groom', 'cat',
      '给小猫轻轻梳梳毛', 'The cat likes a gentle brush.', '小猫喜欢轻轻梳毛。', 'Cat!', '小猫！',
      '再叫一次小猫，请软刷子给它梳梳毛。',
      '小刷子轻轻划过，小猫舒服地眯起眼睛，身边冒出了小爱心。', 'Good!'),
    meetAnimal('a-dog-dry', 2, 'animals-camp', 'animal-dog-shake', 'dog',
      '帮小狗甩掉小水珠', 'A splashy little dog!', '一只沾了小水珠的狗！', 'Dog!', '小狗！',
      '再叫一次小狗，请它甩掉毛上的小水珠。',
      '小狗摇摇身体，小水珠变成了闪闪的星星。现在干爽啦！', 'Great job!'),
    meetAnimal('a-rabbit-bed', 2, 'animals-camp', 'animal-rabbit-rest', 'rabbit',
      '送小兔子去软窝休息', 'A cozy bed for the rabbit.', '给小兔子一个舒服的小窝。', 'Rabbit!', '兔子！',
      '再叫一次兔子，送它去软窝里休息。',
      '小兔子跳进小窝，缩成一个暖暖的小毛球，长耳朵也放松啦。', 'Well done!'),
    meetAnimal('a-duck-dance', 2, 'animals-camp', 'animal-duck-duet', 'duck',
      '邀请鸭子和小鸟跳双人舞', 'The duck wants to dance!', '小鸭子想跳舞！', 'Duck!', '鸭子！',
      '再叫一次鸭子，请它和小鸟一起跳舞。',
      '小鸭子摆摆脚，小鸟绕着它飞，两个小伙伴跳起了有趣的双人舞。', 'Cool!'),
    meetAnimal('a-finale', 2, 'animals-camp', 'animal-party', 'animals',
      '让六个动物朋友一起庆祝', 'Do you like animals?', '你喜欢动物吗？', 'I like animals.', '我喜欢动物。',
      '跟艾莎说我喜欢动物，邀请朋友参加派对。',
      '六个动物一起为你欢呼！谢谢你，小小动物好朋友！', 'You did it!'),
  ],
};
