import type { CommunityRole, LevelConfig, Step, ThemeMoment, World } from './level';

function help(id: string, act: number, world: World, type: ThemeMoment['type'], focus: CommunityRole | 'community',
  title: string, target: string, meaning: string, coach: string, success: string, praise: string, npc = target, translation = meaning): Step {
  return { id, act, world, kind: 'say', title, npc, translation, target, meaning, coach, tip: coach,
    success, praise, effect: 'community', moment: { type, focus }, holdMs: 6200 };
}

/** Original helping story, using the six community-worker words from New Big Fun 1 Unit 8. */
export const LEVEL_7: LevelConfig = {
  id: 7, title: '艾莎的魔法小镇', theme: 'community', spells: false, units: ['BF1-U8'],
  intro: { heading: '叫一叫职业伙伴，<br>和艾莎一起帮帮忙！',
    description: '坐上小巴士，陪小鸭子过街，再到玩偶诊所照顾小熊。六位职业伙伴各有小本领，最后一起参加星光感谢派对。' },
  starStepIds: ['m-bus-ride', 'm-see-doctor', 'm-thanks'],
  acts: [
    { title: '晨光巴士街', subtitle: 'Meet our town helpers', icon: 'flag', world: 'community-street', unit: 'BF1-U8' },
    { title: '泡泡玩偶诊所', subtitle: 'Gentle care for teddy', icon: 'heart', world: 'community-clinic', unit: 'BF1-U8' },
    { title: '星光感谢广场', subtitle: 'Thank you, helpers!', icon: 'sparkles', world: 'community-plaza', unit: 'BF1-U8' },
  ],
  steps: [
    help('m-hello', 0, 'community-street', 'community-hello', 'bus-driver',
      '向小镇伙伴打招呼', 'Hello!', '你好！',
      '和小镇伙伴打个招呼，请司机挥挥手吧。', '司机挥挥小手，欢迎你来魔法小镇！', 'Good!'),
    help('m-bus', 0, 'community-street', 'community-bus-door', 'bus-driver',
      '请司机打开巴士门', 'Bus driver!', '巴士司机！',
      '叫一声巴士司机的英语，请他打开小车门。', '小车门滑开了，团团可以上车啦！', 'Good!'),
    help('m-firefighter', 0, 'community-street', 'community-pinwheel', 'firefighter',
      '请消防员转动小风车', 'Firefighter!', '消防员！',
      '叫一声消防员的英语，请他用水转动风车。', '水花推着风车转起来，转呀转！', 'Great job!'),
    help('m-police', 0, 'community-street', 'community-duck-crossing', 'police-officer',
      '请警察陪小鸭子过街', 'Police officer!', '警察！',
      '小鸭子想过街。跟艾莎说警察的英语吧。', '警察陪着小鸭子，沿斑马线慢慢走过去啦。', 'Well done!'),
    help('m-please', 0, 'community-street', 'community-ticket', 'bus-driver',
      '礼貌地领取星星车票', 'Please!', '请！',
      '想坐小巴士吗？说一句请，拿到星星车票。', '星星车票飞到团团手里，可以出发啦！', 'Great job!'),
    help('m-bus-ride', 0, 'community-street', 'community-bus-ride', 'bus-driver',
      '请司机带伙伴兜一圈', 'Bus driver!', '巴士司机！',
      '再叫一次司机，请小巴士带团团去兜风。', '小巴士载着团团出发，第一颗帮忙星光亮啦！', 'Amazing!'),
    help('m-doctor', 1, 'community-clinic', 'community-heartbeat', 'doctor',
      '请医生听听小熊的心跳', 'Doctor!', '医生！',
      '来到玩偶诊所啦。叫一声医生，请他听听小熊。', '咚咚，咚咚！小熊的心跳变成了爱心。', 'Good!'),
    help('m-nurse', 1, 'community-clinic', 'community-blanket', 'nurse',
      '请护士给小熊盖毯子', 'Nurse!', '护士！',
      '叫一声护士的英语，给小熊盖上软毯子。', '软毯子轻轻盖好，小熊暖暖地抱着它。', 'Great job!'),
    help('m-thank-nurse', 1, 'community-clinic', 'community-care-thanks', 'nurse',
      '谢谢照顾小熊的护士', 'Thank you!', '谢谢你！',
      '小熊暖暖的啦。跟艾莎说谢谢，感谢护士。', '护士送来一个小爱心，团团也开心地笑啦！', 'Well done!'),
    help('m-dentist', 1, 'community-clinic', 'community-tooth-brush', 'dentist',
      '请牙医刷刷玩具牙齿', 'Dentist!', '牙医！',
      '叫一声牙医的英语，请他刷刷这颗玩具牙齿。', '小刷子轻轻刷，玩具牙齿笑得亮晶晶！', 'Well done!'),
    help('m-see-doctor', 1, 'community-clinic', 'community-doctor-introduce', 'doctor',
      '把医生介绍给艾莎', 'I see a doctor.', '我看见一位医生。',
      '你看见谁啦？跟艾莎说，我看见一位医生。', '医生挥挥手，送给你第二颗帮忙星光！', 'Amazing!', 'What do you see?', '你看见什么？'),
    help('m-see-nurse', 2, 'community-plaza', 'community-nurse-lantern', 'nurse',
      '请护士送来暖暖的小灯', 'I see a nurse.', '我看见一位护士。',
      '护士也来派对啦。跟艾莎说，我看见一位护士。', '护士送来暖暖的小灯，大家围过来啦！', 'Good!', 'What do you see?', '你看见什么？'),
    help('m-dentist-bubbles', 2, 'community-plaza', 'community-smile-bubbles', 'dentist',
      '让牙医吹出笑脸泡泡', 'Dentist!', '牙医！',
      '再叫一次牙医，请他把笑脸变成小泡泡。', '圆圆的笑脸泡泡飘起来，大家都笑啦！', 'Cool!'),
    help('m-police-stars', 2, 'community-plaza', 'community-star-path', 'police-officer',
      '请警察点亮星星小路', 'Police officer!', '警察！',
      '再叫一次警察，请他带团团走星星小路。', '星星一颗颗亮起，团团走到了派对中间。', 'Well done!'),
    help('m-firefighter-garden', 2, 'community-plaza', 'community-flower-water', 'firefighter',
      '请消防员浇开派对大花', 'Firefighter!', '消防员！',
      '再叫一次消防员，请他给派对的大花浇水。', '大花喝到水，开出一朵橙色的笑脸！', 'Great job!'),
    help('m-thanks', 2, 'community-plaza', 'community-thank-you', 'community',
      '感谢六位小镇伙伴', 'Thank you!', '谢谢你们！',
      '六位伙伴都帮了忙。跟艾莎说一句谢谢吧。', '六位伙伴一起挥手。谢谢你，小小帮帮员！', 'You did it!'),
  ],
};
