import type { LevelConfig, Step, ThemeMoment, Toy, World } from './level';

function toyStep(
  id: string, act: number, world: World, type: ThemeMoment['type'], focus: Toy | 'toys',
  title: string, npc: string, translation: string, target: string, meaning: string,
  coach: string, success: string, praise: string,
): Step {
  return { id, act, world, kind: 'say', title, npc, translation, target, meaning,
    coach, tip: coach, effect: 'toys', success, moment: { type, focus }, praise,
    holdMs: type === 'toy-parade' ? 5800 : type === 'toy-train-ride' ? 4800 : 4000 };
}

/** One toy adventure, with recognition, ownership and review woven into different actions. */
export const LEVEL_4: LevelConfig = {
  id: 4, title: '玩具城堡', theme: 'toys', spells: false,
  intro: {
    heading: '和团团一起，<br>叫醒玩具小伙伴！',
    description: '玩具们想去彩虹街游行。先帮球、小熊和玩偶醒过来，再用积木修好火车轨道，带大家一起出发！',
  },
  units: ['BF1-U4'], starStepIds: ['t-my-ball', 't-my-train', 't-finale'],
  acts: [
    { title: '惊喜玩具屋', subtitle: 'Wake up, little toys!', icon: 'heart', world: 'toys-room', unit: 'BF1-U4' },
    { title: '齿轮火车站', subtitle: 'Build, drive & ride', icon: 'sparkles', world: 'toys-station', unit: 'BF1-U4' },
    { title: '彩虹游行街', subtitle: 'Our toy parade', icon: 'flag', world: 'toys-parade', unit: 'BF1-U4' },
  ],
  steps: [
    toyStep('t-ball', 0, 'toys-room', 'toy-ball-bounce', 'ball',
      '叫醒弹跳的小球', 'Look! A ball!', '看，一个球！', 'Ball!', '球！',
      '团团的玩具要去游行。小球还没醒呢，跟艾莎叫一声小球的英语吧。',
      '咚、咚、咚！小球醒过来，开心地跳了三下。', 'Good!'),
    toyStep('t-teddy', 0, 'toys-room', 'toy-teddy-hug', 'teddy',
      '请小熊送来一个抱抱', 'A teddy bear!', '一只泰迪熊！', 'Teddy bear!', '泰迪熊！',
      '软软的小熊也想参加。跟着叫它的名字，它会给团团一个温暖的抱抱。',
      '小熊靠过来抱抱团团，头顶冒出小爱心。', 'Great job!'),
    toyStep('t-doll', 0, 'toys-room', 'toy-doll-spin', 'doll',
      '邀请玩偶转个圈', 'Here is a doll.', '这里有一个玩偶。', 'Doll!', '玩偶！',
      '玩偶穿好了小裙子。叫一声玩偶的英语，邀请它跳一支小小的舞。',
      '玩偶轻轻转圈，裙子旁边飞出亮晶晶的星星。', 'Well done!'),
    toyStep('t-my-ball', 0, 'toys-room', 'toy-ball-roll', 'ball',
      '和自己的小球玩一玩', 'Is it your ball?', '这是你的球吗？', "It's my ball.", '这是我的球。',
      '小球想和你一起玩。跟艾莎说这是我的球，它就会滚来找团团。',
      '小球滚过来，又滚回去。你和团团一起玩传球啦！', 'Amazing!'),
    toyStep('t-blocks', 1, 'toys-station', 'toy-blocks-build', 'blocks',
      '用积木修好小轨道', 'We need blocks.', '我们需要积木。', 'Blocks!', '积木！',
      '火车轨道缺了一小段。叫一声积木的英语，帮玩具搭好出发的小桥。',
      '积木一块一块搭起来，小桥和轨道接好啦。', 'Good!'),
    toyStep('t-car', 1, 'toys-station', 'toy-car-drive', 'car',
      '请小汽车试试新路', 'Here comes a car!', '小汽车来啦！', 'Car!', '小汽车！',
      '小汽车想试试新路。跟着说小汽车的英语，让它开过去看看。',
      '嘟嘟！小汽车开了一个来回，给你带回一串小星星。', 'Cool!'),
    toyStep('t-train', 1, 'toys-station', 'toy-train-start', 'train',
      '叫醒准备出发的火车', 'Look at the train.', '看看这辆火车。', 'Train!', '火车！',
      '轨道准备好了。叫一声火车的英语，让小火车吐出软软的云朵。',
      '呜呜！烟囱冒出云朵，小火车准备来接玩具们。', 'Well done!'),
    toyStep('t-my-train', 1, 'toys-station', 'toy-train-ride', 'train',
      '带着玩具坐上小火车', 'Is it your train?', '这是你的火车吗？', "It's my train.", '这是我的火车。',
      '说说这是我的火车，带玩具去彩虹街吧。',
      '小球、小熊和玩偶坐上车厢，一起去彩虹街啦！', 'Amazing!'),
    toyStep('t-doll-parade', 2, 'toys-parade', 'toy-doll-conduct', 'doll',
      '请玩偶挥动游行彩带', 'The doll is ready.', '玩偶准备好了。', 'Doll!', '玩偶！',
      '彩虹街的游行要开始了。再叫一声玩偶的名字，请它挥起彩带。',
      '玩偶挥起彩带，彩虹街亮起了小星星。', 'Good!'),
    toyStep('t-teddy-parade', 2, 'toys-parade', 'toy-teddy-cheer', 'teddy',
      '让小熊为大家加油', 'The teddy bear is happy.', '泰迪熊很开心。', 'Teddy bear!', '泰迪熊！',
      '小熊想给大家加油。再叫一声它的名字，看看它会怎么庆祝。',
      '小熊摇摇小耳朵，给游行送来一大串爱心。', 'Great job!'),
    toyStep('t-ball-parade', 2, 'toys-parade', 'toy-ball-confetti', 'ball',
      '让小球跳出彩纸雨', 'The ball can bounce!', '小球会弹跳！', 'Ball!', '球！',
      '小球也想加入庆祝。跟着说球的英语，它这次会跳出彩色纸片。',
      '小球高高跳起来，彩色纸片像小雨一样落下来。', 'Cool!'),
    toyStep('t-car-parade', 2, 'toys-parade', 'toy-car-carry', 'car',
      '请汽车载小熊去游行', 'The car is ready.', '小汽车准备好了。', 'Car!', '小汽车！',
      '小熊想坐汽车游行。再叫一声小汽车的英语，请它载着小熊出发。',
      '小熊坐上小汽车，摇摇晃晃地向大家招手。', 'Well done!'),
    toyStep('t-finale', 2, 'toys-parade', 'toy-parade', 'toys',
      '和全部玩具一起游行', 'Do you like your toys?', '你喜欢你的玩具吗？', 'I like my toys.', '我喜欢我的玩具。',
      '六个玩具都来啦。跟艾莎说我喜欢我的玩具，让大家一起走过彩虹街。',
      '球、玩偶、小熊、汽车、火车和积木，一起参加你的玩具大游行！', 'You did it!'),
  ],
};
