import type { Clothing, LevelConfig, Step, ThemeMoment, WardrobeChange, World } from './level';

function dressUp(
  id: string, act: number, world: World, type: ThemeMoment['type'], focus: Clothing | 'clothes',
  title: string, npc: string, translation: string, target: string, meaning: string,
  coach: string, success: string, praise: string, wardrobe?: WardrobeChange,
): Step {
  return { id, act, world, kind: 'say', title, npc, translation, target, meaning,
    coach, tip: coach, effect: 'clothes', success, praise, moment: { type, focus, wardrobe },
    holdMs: type === 'wardrobe-dance' ? 5800 : type === 'wardrobe-portrait' ? 4800 : 4000 };
}

/** Clothing words change the outfit; later repetitions create new story outcomes. */
export const LEVEL_5: LevelConfig = {
  id: 5, title: '艾莎的魔法衣橱', theme: 'clothes', spells: false,
  intro: {
    heading: '帮艾莎换新衣，<br>一起去魔法舞会！',
    description: '艾莎收到了一张舞会邀请！用声音打开魔法衣橱，搭配衣服、鞋帽，穿过小花园，最后和团团一起跳舞。',
  },
  units: ['BF1-U6'], starStepIds: ['c-my-dress', 'c-my-coat', 'c-finale'],
  acts: [
    { title: '魔法衣橱', subtitle: 'Dress, shoes & hat', icon: 'heart', world: 'wardrobe-closet', unit: 'BF1-U6' },
    { title: '花园试衣亭', subtitle: 'A little garden surprise', icon: 'sparkles', world: 'wardrobe-garden', unit: 'BF1-U6' },
    { title: '星光舞会', subtitle: 'I like my dress!', icon: 'flag', world: 'wardrobe-ball', unit: 'BF1-U6' },
  ],
  steps: [
    dressUp('c-dress', 0, 'wardrobe-closet', 'wardrobe-dress', 'dress',
      '变出一条花花连衣裙', 'Look! A dress!', '看，一条连衣裙！', 'Dress!', '连衣裙！',
      '叫一声连衣裙的英语，帮艾莎换上花花裙。',
      '花花连衣裙飞过来，艾莎换上了粉色的新裙子！', 'Good!', { look: 'dress' }),
    dressUp('c-shoes', 0, 'wardrobe-closet', 'wardrobe-shoes', 'shoes',
      '请小鞋子飞到脚上', 'Here are my shoes.', '这是我的鞋子。', 'Shoes!', '鞋子！',
      '说说鞋子的英语，让小鞋飞到艾莎脚上。',
      '两只小鞋飞到艾莎的脚上，她开心地踮了踮脚。', 'Great job!', { shoes: 'pink' }),
    dressUp('c-hat', 0, 'wardrobe-closet', 'wardrobe-hat', 'hat',
      '戴上花朵小帽子', 'A pretty hat!', '一顶漂亮的帽子！', 'Hat!', '帽子！',
      '叫一声帽子的英语，请小帽子飞过来。',
      '小帽子转了一圈，轻轻落在艾莎的头上。', 'Well done!', { hat: true }),
    dressUp('c-my-dress', 0, 'wardrobe-closet', 'wardrobe-mirror', 'dress',
      '照镜子看看新裙子', 'Show me your dress.', '让我看看你的连衣裙。', 'My dress.', '我的连衣裙。',
      '跟艾莎说我的连衣裙，让镜子照照新搭配。',
      '镜子里的艾莎点点头，第一颗装扮星光亮啦！', 'Amazing!'),
    dressUp('c-shirt', 1, 'wardrobe-garden', 'wardrobe-shirt', 'shirt',
      '换上轻松的小衬衫', 'Here is a shirt.', '这里有一件衬衫。', 'Shirt!', '衬衫！',
      '叫一声衬衫的英语，换上黄色小衬衫。',
      '黄色小衬衫穿好啦，艾莎可以轻轻松松地逛花园。', 'Good!', { look: 'shirt' }),
    dressUp('c-skirt', 1, 'wardrobe-garden', 'wardrobe-skirt', 'skirt',
      '让半身裙开出花瓣', 'Look at the skirt.', '看看这条半身裙。', 'Skirt!', '半身裙！',
      '说说半身裙的英语，让紫色小裙子来搭配。',
      '半身裙变成紫色的，艾莎轻轻转身，花瓣也跟着飞起来。', 'Cool!', { look: 'skirt' }),
    dressUp('c-coat', 1, 'wardrobe-garden', 'wardrobe-coat', 'coat',
      '用外套接住小雨点', 'We need a coat.', '我们需要一件外套。', 'Coat!', '外套！',
      '下小雨啦。说说外套的英语，帮艾莎穿好。',
      '薄荷绿外套穿上啦，小雨点在衣服上跳来跳去。', 'Well done!', { look: 'coat' }),
    dressUp('c-my-coat', 1, 'wardrobe-garden', 'wardrobe-rainbow', 'coat',
      '把小雨变成彩虹', 'Show me your coat.', '让我看看你的外套。', 'My coat.', '我的外套。',
      '跟艾莎说我的外套，邀请彩虹出来吧。',
      '小雨停了，花园出现一道彩虹。第二颗装扮星星亮起来！', 'Amazing!'),
    dressUp('c-party-dress', 2, 'wardrobe-ball', 'wardrobe-ballgown', 'dress',
      '穿上亮晶晶的舞会裙', 'A dress for the party!', '一条参加舞会的连衣裙！', 'Dress!', '连衣裙！',
      '舞会开始啦。再叫一次连衣裙，变出礼服。',
      '冰雪礼服闪闪发光，艾莎准备好去跳舞啦！', 'Great job!', { look: 'ballgown' }),
    dressUp('c-party-shoes', 2, 'wardrobe-ball', 'wardrobe-footsteps', 'shoes',
      '跟着小鞋子走舞步', 'My dancing shoes!', '我的跳舞鞋！', 'Shoes!', '鞋子！',
      '再说一次鞋子的英语，请舞鞋走星星舞步。',
      '舞鞋闪起来，艾莎跟着星星脚印轻轻走了三步。', 'Cool!', { shoes: 'sparkle' }),
    dressUp('c-hat-away', 2, 'wardrobe-ball', 'wardrobe-hat-away', 'hat',
      '让帽子去衣架休息', 'Thank you, little hat!', '谢谢你，小帽子！', 'Hat!', '帽子！',
      '再叫一次帽子的英语，送它飞回小衣架。',
      '帽子飞回小衣架，轻轻摇了摇，好像在为艾莎加油。', 'Well done!', { hat: false }),
    dressUp('c-photo', 2, 'wardrobe-ball', 'wardrobe-portrait', 'dress',
      '留下自己的舞会照片', 'Show me your dress.', '让我看看你的连衣裙。', 'My dress.', '我的连衣裙。',
      '说说我的连衣裙，给新搭配拍张照片吧。',
      '相框里留下了艾莎的新裙子和舞鞋。这是你帮她完成的装扮！', 'Amazing!'),
    dressUp('c-finale', 2, 'wardrobe-ball', 'wardrobe-dance', 'clothes',
      '和艾莎一起参加舞会', 'Do you like your dress?', '你喜欢你的连衣裙吗？', 'I like my dress.', '我喜欢我的连衣裙。',
      '跟艾莎说我喜欢我的连衣裙，一起跳舞吧。',
      '艾莎和团团跳起舞，谢谢你，小小魔法造型师！', 'You did it!'),
  ],
};
